language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@6.1.0

script:
  # TODO: Change this to "npm test" once our tests are no longer failing.
  #       "npm test" includes running eslint.
  - npm run eslint