language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - "$HOME/.npm"

env:
  - MONGO_URL=mongodb://127.0.0.1:27017/gamification

install:
  - npm ci

before_install:
  - npm i -g npm@6.1.0

services:
  - mongodb

script:
  - npm run test
  - nyc report --reporter=text-lcov | coveralls
