version: '3'
services:
  mongo:
    image: mongo:3.6.5
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./dev/rabbitmq-config:/etc/rabbitmq
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: gamification:dev
    volumes:
      - ./:/app
    ports:
      - "3030:3030"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGO_URL=mongodb://mongo/gamification
      - RABBITMQ_HOST=rabbitmq
volumes:
  mongo-data:
  rabbitmq_log:
  rabbitmq_data:
