version: '3'
services:
  mongo:
    image: mongo:3.6.5
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    image: gamification
    volumes:
      - ./:/app
    command: npm start
    ports:
      - "3030:3030"
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGO_URL=mongodb://mongo/gamification
      - RABBITMQ_HOST=rabbitmq
volumes:
  mongo-data:
  rabbitmq_log:
  rabbitmq_data:
