version: '3'
services:
  mongo:
    image: mongo:3.6.5
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  app:
    build: .
    image: gamification
    volumes:
      - ./:/app
    command: nodemon npm start
    ports:
      - "3030:3030"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/gamification
volumes:
  mongo-data:
